version: "3.7"

services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["uvicorn", "main:app", "--host=0.0.0.0", "--reload"]
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ~/.ssh/id_rsa_cryptopie:/root/.ssh/id_rsa
